import React from 'react'

export const metadata = {
  title: 'About',
  description: 'Generated by Next.js',
}

const About = () => {
  return (
    <div>This is the About page</div>
  )
}

export default About